@startuml
'https://plantuml.com/class-diagram

interface Mediator {
    sendMessage(message: String): void
}

class MediatorImpl implements Mediator{
    - colleagues: List<Colleague>

    + sendMessage(message: string, sender: Colleague): void
}

interface Colleague {
    sendMessage(message: String): void
    receiveMessage(message: String): void
}

class ColleagueImpl implements Colleague {
    - mediator: Mediator

    + ColleagueImpl(mediator: Mediator)

    + sendMessage(message: String): void
    + receiveMessage(message: String): void
}

Colleague "*" o..o "1" Mediator: has

@enduml